const production = false
const configuredDerivAppId = Number(
  process.env.NEXT_PUBLIC_DERIV_OAUTH_CLIENT_ID ||
  process.env.NEXT_PUBLIC_DERIV_CLIENT_ID ||
  process.env.NEXT_PUBLIC_DERIV_APP_ID
)

export const myPref = {
  appId: 53052 ,
  wsUrl: "wss://ws.derivws.com/websockets/v3?app_id=",
  oauthUrl: "https://auth.deriv.com/oauth2/auth",
  oauthScope: "trade account_manage",
}

export const KEYS = {
    TENOR_API_KEY: "AIzaSyAMc5bo6Oitet5gur9RHgN2mktjvdO9TRU",
    TENOR_APP_NAME: "Aviator",
    JWT_SECRET: "topwebtools_aviator_game_api"
}

export const emojiCategories = {
    favorites: [
      { emoji: "😊", name: "Smiling Face with Smiling Eyes" },
      { emoji: "😂", name: "Face with Tears of Joy" },
      { emoji: "❤️", name: "Red Heart" },
      { emoji: "😍", name: "Smiling Face with Heart-Eyes" },
      { emoji: "😎", name: "Smiling Face with Sunglasses" },
      { emoji: "🥳", name: "Partying Face" },
      { emoji: "😢", name: "Crying Face" },
      { emoji: "😡", name: "Pouting Face" },
      { emoji: "👍", name: "Thumbs Up" },
      { emoji: "👎", name: "Thumbs Down" },
      { emoji: "🙌", name: "Raising Hands" },
      { emoji: "🎉", name: "Party Popper" },
      { emoji: "✨", name: "Sparkles" },
      { emoji: "🔥", name: "Fire" },
      { emoji: "💯", name: "Hundred Points" },
      { emoji: "🙏", name: "Folded Hands" },
      { emoji: "🎊", name: "Confetti Ball" },
      { emoji: "😇", name: "Smiling Face with Halo" },
      { emoji: "🤔", name: "Thinking Face" },
      { emoji: "💔", name: "Broken Heart" },
      { emoji: "🌈", name: "Rainbow" },
    ],
    people: [
      // Smileys & Emotion
      { emoji: "😀", name: "Grinning Face" },
      { emoji: "😁", name: "Beaming Face with Smiling Eyes" },
      { emoji: "😂", name: "Face with Tears of Joy" },
      { emoji: "🤣", name: "Rolling on the Floor Laughing" },
      { emoji: "😃", name: "Grinning Face with Big Eyes" },
      { emoji: "😄", name: "Grinning Face with Smiling Eyes" },
      { emoji: "😅", name: "Grinning Face with Sweat" },
      { emoji: "😆", name: "Grinning Squinting Face" },
      { emoji: "😉", name: "Winking Face" },
      { emoji: "😊", name: "Smiling Face with Smiling Eyes" },
      { emoji: "😋", name: "Face Savoring Food" },
      { emoji: "😎", name: "Smiling Face with Sunglasses" },
      { emoji: "😍", name: "Heart Eyes" },
      { emoji: "😘", name: "Face Blowing a Kiss" },
      { emoji: "😗", name: "Kissing Face" },
      { emoji: "😙", name: "Kissing Face with Smiling Eyes" },
      { emoji: "😚", name: "Kissing Face with Closed Eyes" },
      { emoji: "🙂", name: "Slightly Smiling Face" },
      { emoji: "🤗", name: "Hugging Face" },
      { emoji: "🤩", name: "Star-Struck" },
      { emoji: "🥳", name: "Partying Face" },
      { emoji: "😏", name: "Smirking Face" },
      { emoji: "😒", name: "Unamused Face" },
      { emoji: "😞", name: "Disappointed Face" },
      { emoji: "😔", name: "Pensive Face" },
      { emoji: "😟", name: "Worried Face" },
      { emoji: "😕", name: "Confused Face" },
      { emoji: "🙁", name: "Slightly Frowning Face" },
      { emoji: "☹️", name: "Frowning Face" },
      { emoji: "😣", name: "Persevering Face" },
      { emoji: "😖", name: "Confounded Face" },
      { emoji: "😫", name: "Tired Face" },
      { emoji: "😩", name: "Weary Face" },
      { emoji: "🥺", name: "Pleading Face" },
      { emoji: "😢", name: "Crying Face" },
      { emoji: "😭", name: "Loudly Crying Face" },
      { emoji: "😤", name: "Face with Steam From Nose" },
      { emoji: "😠", name: "Angry Face" },
      { emoji: "😡", name: "Pouting Face" },
      { emoji: "🤬", name: "Face with Symbols on Mouth" },
      { emoji: "😳", name: "Flushed Face" },
      { emoji: "🥵", name: "Hot Face" },
      { emoji: "🥶", name: "Cold Face" },
      { emoji: "😱", name: "Face Screaming in Fear" },
      { emoji: "😨", name: "Fearful Face" },
      { emoji: "😰", name: "Anxious Face with Sweat" },
      { emoji: "😥", name: "Sad but Relieved Face" },
      { emoji: "😓", name: "Downcast Face with Sweat" },
      { emoji: "🤔", name: "Thinking Face" },
      { emoji: "🤭", name: "Face with Hand Over Mouth" },
      { emoji: "🤫", name: "Shushing Face" },
      { emoji: "🤥", name: "Lying Face" },
      { emoji: "🤢", name: "nauseated face" },
      { emoji: "🤮", name: "face vomiting" },
      { emoji: "🤧", name: "sneezing face" },
      { emoji: "😷", name: "face with medical mask" },
      { emoji: "🤒", name: "face with thermometer" },
      { emoji: "🤕", name: "face with head-bandage" },
      { emoji: "🤑", name: "money-mouth face" },
      { emoji: "🤠", name: "cowboy hat face" },
      { emoji: "😈", name: "smiling face with horns" },
      { emoji: "👿", name: "angry face with horns" },
      { emoji: "👹", name: "ogre" },
      { emoji: "👺", name: "goblin" },
      { emoji: "🤡", name: "clown face" },
      { emoji: "💩", name: "pile of poo" },
      { emoji: "👻", name: "ghost" },
      { emoji: "💀", name: "skull" },
      { emoji: "☠️", name: "skull and crossbones" },
      { emoji: "👽", name: "alien" },
      { emoji: "👾", name: "space invader" },
      { emoji: "🤖", name: "robot face" },
      { emoji: "🎃", name: "jack-o-lantern" },
      { emoji: "😺", name: "grinning cat face" },
      { emoji: "😸", name: "grinning cat face with smiling eyes" },
      { emoji: "😹", name: "cat with tears of joy" },
      { emoji: "😻", name: "smiling cat face with heart-eyes" },
      { emoji: "😼", name: "cat face with wry smile" },
      { emoji: "😽", name: "kissing cat face" },
      { emoji: "🙀", name: "weary cat face" },
      { emoji: "😿", name: "crying cat face" },
      { emoji: "😾", name: "pouting cat face" },
  
      // Hand Signs
      { emoji: "👍", name: "Thumbs Up" },
      { emoji: "👎", name: "Thumbs Down" },
      { emoji: "👊", name: "Oncoming Fist" },
      { emoji: "✊", name: "Raised Fist" },
      { emoji: "🤛", name: "Left-Facing Fist" },
      { emoji: "🤜", name: "Right-Facing Fist" },
      { emoji: "👏", name: "Clapping Hands" },
      { emoji: "🙌", name: "Raising Hands" },
      { emoji: "👐", name: "Open Hands" },
      { emoji: "🤲", name: "Palms Up Together" },
      { emoji: "🤝", name: "Handshake" },
      { emoji: "🙏", name: "Folded Hands" },
      { emoji: "✌️", name: "Victory Hand" },
      { emoji: "🤞", name: "Crossed Fingers" },
      { emoji: "🤟", name: "Love-You Gesture" },
      { emoji: "🤘", name: "Sign of the Horns" },
      { emoji: "👌", name: "OK Hand" },
      { emoji: "👈", name: "Backhand Index Pointing Left" },
      { emoji: "👉", name: "Backhand Index Pointing Right" },
      { emoji: "👆", name: "Backhand Index Pointing Up" },
      { emoji: "👇", name: "Backhand Index Pointing Down" },
      { emoji: "☝️", name: "Index Pointing Up" },
      { emoji: "✋", name: "Raised Hand" },
      { emoji: "🤚", name: "Raised Back of Hand" },
      { emoji: "🖐️", name: "Hand with Fingers Splayed" },
      { emoji: "🖖", name: "Vulcan Salute" },
      { emoji: "🤏", name: "Pinching Hand" },
      { emoji: "👋", name: "Waving Hand" },
      { emoji: "💪", name: "Flexed Biceps" },
      { emoji: "🫰", name: "Hand with Fingers Spread" },
      { emoji: "🤙", name: "Call Me Hand" },
      { emoji: "🫵", name: "Index Pointing at You" },
      { emoji: "🫱", name: "Right-Facing Hand" },
      { emoji: "🫲", name: "Left-Facing Hand" },
      { emoji: "🫸", name: "Down-Facing Hand" },
      { emoji: "🫷", name: "Up-Facing Hand" },
      { emoji: "🫳", name: "Pinching Hand" },
      { emoji: "🫴", name: "Hand with Fingers Spread" },
      { emoji: "🦾", name: "Mechanical Arm" },
      { emoji: "🦵", name: "Monkey Face" },
      { emoji: "🦿", name: "Mechanical Leg" },
      { emoji: "🦶", name: "Foot" },
      { emoji: "👣", name: "Footprints" },
      { emoji: "👂", name: "Mouth" },
      { emoji: "🦻", name: "Ear" },
      { emoji: "👃", name: "Nose" },
      { emoji: "🫀", name: "Heart" },
      { emoji: "🫁", name: "Lungs" },
      { emoji: "🧠", name: "Brain" },
      { emoji: "🦷", name: "Bird" },
      { emoji: "🦴", name: "Bone" },
      { emoji: "👀", name: "Eyes" },
      { emoji: "👁", name: "Eye" },
      { emoji: "👅", name: "Tongue" },
      { emoji: "👄", name: "Mouth" },
      { emoji: "🫦", name: "Lips" },
      { emoji: "💋", name: "Kiss Mark" },
      { emoji: "🩸", name: "Drop of Blood" },
  
      // Hearts
      { emoji: "❤️", name: "Red Heart" },
      { emoji: "🧡", name: "Orange Heart" },
      { emoji: "💛", name: "Yellow Heart" },
      { emoji: "💚", name: "Green Heart" },
      { emoji: "💙", name: "Blue Heart" },
      { emoji: "💜", name: "Purple Heart" },
      { emoji: "🤎", name: "Brown Heart" },
      { emoji: "🖤", name: "Black Heart" },
      { emoji: "🤍", name: "White Heart" },
      { emoji: "💔", name: "Broken Heart" },
      { emoji: "❣️", name: "Heart Exclamation" },
      { emoji: "💕", name: "Two Hearts" },
      { emoji: "💞", name: "Revolving Hearts" },
      { emoji: "💓", name: "Beating Heart" },
      { emoji: "💗", name: "Growing Heart" },
      { emoji: "💖", name: "Sparkling Heart" },
      { emoji: "💘", name: "Heart with Arrow" },
      { emoji: "💝", name: "Heart with Ribbon" },

      // People
        { emoji: "👶", name: "Baby" },
        { emoji: "👧", name: "Girl" },
        { emoji: "🧒", name: "Child" },
        { emoji: "👦", name: "Boy" },
        { emoji: "👩", name: "Woman" },
        { emoji: "🧑", name: "Person" },
        { emoji: "👨", name: "Man" },
        { emoji: "👩‍🦱", name: "Woman with Curly Hair" },
        { emoji: "🧑‍🦱", name: "Person with Curly Hair" },
        { emoji: "👨‍🦱", name: "Man with Curly Hair" },
        { emoji: "👩‍🦰", name: "Woman with Red Hair" },
        { emoji: "🧑‍🦰", name: "Person with Red Hair" },
        { emoji: "👨‍🦰", name: "Man with Red Hair" },
        { emoji: "👱‍♀️", name: "Woman with Blond Hair" },
        { emoji: "👱", name: "Person with Blond Hair" },
        { emoji: "👱‍♂️", name: "Man with Blond Hair" },
        { emoji: "👩‍🦳", name: "Woman with White Hair" },
        { emoji: "🧑‍🦳", name: "Person with White Hair" },
        { emoji: "👨‍🦳", name: "Man with White Hair" },
        { emoji: "👩‍🦲", name: "Woman with Bald Head" },
        { emoji: "🧑‍🦲", name: "Person with Bald Head" },
        { emoji: "👨‍🦲", name: "Man with Bald Head" },
        { emoji: "🧔‍♀️", name: "Woman with Beard" },
        { emoji: "🧔", name: "Person with Beard" },
        { emoji: "🧔‍♂️", name: "Man with Beard" },
        { emoji: "👵", name: "Older Woman" },
        { emoji: "🧓", name: "Older Person" },
        { emoji: "👴", name: "Older Man" },
        { emoji: "👲", name: "Person with Turban" },
        { emoji: "👳‍♀️", name: "Woman with Turban" },
        { emoji: "👳", name: "Person with Turban" },
        { emoji: "👳‍♂️", name: "Man with Turban" },
        { emoji: "🧕", name: "Person with Headscarf" },
        { emoji: "👮‍♀️", name: "Woman Police Officer" },
        { emoji: "👮", name: "Police Officer" },
        { emoji: "👮‍♂️", name: "Man Police Officer" },
        { emoji: "👷‍♀️", name: "Woman Construction Worker" },
        { emoji: "👷", name: "Construction Worker" },
        { emoji: "👷‍♂️", name: "Man Construction Worker" },
        { emoji: "💂‍♀️", name: "Woman Guard" },
        { emoji: "💂", name: "Guard" },
        { emoji: "💂‍♂️", name: "Man Guard" },
        { emoji: "🕵️‍♀️", name: "Woman Detective" },
        { emoji: "🕵️", name: "Detective" },
        { emoji: "🕵️‍♂️", name: "Man Detective" },
        { emoji: "👩‍⚕️", name: "Woman Health Worker" },
        { emoji: "🧑‍⚕️", name: "Person Health Worker" },
        { emoji: "👨‍⚕️", name: "Man Health Worker" },
        { emoji: "👩‍🌾", name: "Woman Farmer" },
        { emoji: "🧑‍🌾", name: "Person Farmer" },
        { emoji: "👨‍🌾", name: "Man Farmer" },
        { emoji: "👩‍🍳", name: "Woman Cook" },
        { emoji: "🧑‍🍳", name: "Person Cook" },
        { emoji: "👨‍🍳", name: "Man Cook" },
        { emoji: "👩‍🎓", name: "Woman Student" },
        { emoji: "🧑‍🎓", name: "Person Student" },
        { emoji: "👨‍🎓", name: "Man Student" },
        { emoji: "👩‍🎤", name: "Woman Singer" },
        { emoji: "🧑‍🎤", name: "Person Singer" },
        { emoji: "👨‍🎤", name: "Man Singer" },
        { emoji: "👩‍🏫", name: "Woman Teacher" },
        { emoji: "🧑‍🏫", name: "Person Teacher" },
        { emoji: "👨‍🏫", name: "Man Teacher" },
        { emoji: "👩‍🏭", name: "Woman Factory Worker" },
        { emoji: "🧑‍🏭", name: "Person Factory Worker" },
        { emoji: "👨‍🏭", name: "Man Factory Worker" },
        { emoji: "👩‍💻", name: "Woman Technologist" },
        { emoji: "🧑‍💻", name: "Person Technologist" },
        { emoji: "👨‍💻", name: "Man Technologist" },
        { emoji: "👩‍💼", name: "Woman Office Worker" },
        { emoji: "🧑‍💼", name: "Person Office Worker" },
        { emoji: "👨‍💼", name: "Man Office Worker" },
        { emoji: "👩‍🔧", name: "Woman Mechanic" },
        { emoji: "🧑‍🔧", name: "Person Mechanic" },
        { emoji: "👨‍🔧", name: "Man Mechanic" },
        { emoji: "👩‍🔬", name: "Woman Scientist" },
        { emoji: "🧑‍🔬", name: "Person Scientist" },
        { emoji: "👨‍🔬", name: "Man Scientist" },
        { emoji: "👩‍🎨", name: "Woman Artist" },
        { emoji: "🧑‍🎨", name: "Person Artist" },
        { emoji: "👨‍🎨", name: "Man Artist" },
        { emoji: "👩‍🚒", name: "Woman Firefighter" },
        { emoji: "🧑‍🚒", name: "Person Firefighter" },
        { emoji: "👨‍🚒", name: "Man Firefighter" },
        { emoji: "👩‍✈️", name: "Woman Pilot" },
        { emoji: "🧑‍✈️", name: "Person Pilot" },
        { emoji: "👨‍✈️", name: "Man Pilot" },
        { emoji: "👩‍🚀", name: "Woman Astronaut" },
        { emoji: "🧑‍🚀", name: "Person Astronaut" },
        { emoji: "👨‍🚀", name: "Man Astronaut" },
        { emoji: "👩‍⚖️", name: "Woman Judge" },
        { emoji: "🧑‍⚖️", name: "Person Judge" },
        { emoji: "👨‍⚖️", name: "Man Judge" },
      
    ],
    nature: [
      // Animals
      { emoji: "🐶", name: "Dog Face" },
      { emoji: "🐱", name: "Cat Face" },
      { emoji: "🐭", name: "Mouse Face" },
      { emoji: "🐹", name: "Hamster Face" },
      { emoji: "🐰", name: "Rabbit Face" },
      { emoji: "🦊", name: "Fox Face" },
      { emoji: "🐻", name: "Bear Face" },
      { emoji: "🐼", name: "Panda Face" },
      { emoji: "🦁", name: "Lion Face" },
      { emoji: "🐯", name: "Tiger Face" },
      { emoji: "🐨", name: "Koala Face" },
      { emoji: "🐮", name: "Cow Face" },
      { emoji: "🐷", name: "Pig Face" },
      { emoji: "🐸", name: "Frog Face" },
      { emoji: "🐵", name: "Monkey Face" },
      { emoji: "🙈", name: "See-No-Evil Monkey" },
      { emoji: "🙉", name: "Hear-No-Evil Monkey" },
      { emoji: "🙊", name: "Speak-No-Evil Monkey" },
      { emoji: "🐒", name: "Monkey" },
      { emoji: "🐔", name: "Chicken" },
      { emoji: "🐧", name: "Penguin" },
      { emoji: "🐦", name: "Bird" },
      { emoji: "🐤", name: "Baby Chick" },
      { emoji: "🦉", name: "Owl" },
      { emoji: "🐺", name: "Wolf" },
      { emoji: "🐗", name: "Boar" },
      { emoji: "🐴", name: "Horse Face" },
      { emoji: "🦄", name: "Unicorn" },
      { emoji: "🐝", name: "Bee" },
      { emoji: "🐛", name: "Bug" },
      { emoji: "🦋", name: "Butterfly" },
      { emoji: "🐌", name: "Snail" },
      { emoji: "🐞", name: "Lady Beetle" },
      { emoji: "🐜", name: "Ant" },
      { emoji: "🦟", name: "Mosquito" },
      { emoji: "🦗", name: "Cricket" },
      { emoji: "🐢", name: "Turtle" },
      { emoji: "🐍", name: "Snake" },
      { emoji: "🦕", name: "Sauropod" },
      { emoji: "🦖", name: "T-Rex" },
      { emoji: "🦑", name: "Squid" },
      { emoji: "🐙", name: "Octopus" },
      { emoji: "🦞", name: "Lobster" },
      { emoji: "🦐", name: "Shrimp" },
      { emoji: "🐠", name: "Tropical Fish" },
      { emoji: "🐟", name: "Fish" },
      { emoji: "🐡", name: "Blowfish" },
      { emoji: "🐬", name: "Dolphin" },
      { emoji: "🐳", name: "Spouting Whale" },
      { emoji: "🐋", name: "Whale" },
      { emoji: "🦍", name: "Gorilla" },
      { emoji: "🦧", name: "Orangutan" },
  
      // Plants
      { emoji: "🌲", name: "Evergreen Tree" },
      { emoji: "🌳", name: "Deciduous Tree" },
      { emoji: "🌴", name: "Palm Tree" },
      { emoji: "🌵", name: "Cactus" },
      { emoji: "🌾", name: "Sheaf of Rice" },
      { emoji: "🌿", name: "Herb" },
      { emoji: "🍀", name: "Four Leaf Clover" },
      { emoji: "🍁", name: "Maple Leaf" },
      { emoji: "🍂", name: "Fallen Leaf" },
      { emoji: "🍃", name: "Leaf Fluttering in Wind" },
      { emoji: "🍄", name: "Mushroom" },
  
      // Sky & Weather
      { emoji: "☀️", name: "Sun" },
      { emoji: "🌤️", name: "Sun Behind Small Cloud" },
      { emoji: "⛅", name: "Sun Behind Cloud" },
      { emoji: "🌥️", name: "Sun Behind Large Cloud" },
      { emoji: "🌦️", name: "Sun Behind Rain Cloud" },
      { emoji: "🌧️", name: "Cloud with Rain" },
      { emoji: "⛈️", name: "Cloud with Lightning and Rain" },
      { emoji: "🌩️", name: "Cloud with Lightning" },
      { emoji: "🌨️", name: "Cloud with Snow" },
      { emoji: "🌪️", name: "Tornado" },
      { emoji: "🌫️", name: "Fog" },
      { emoji: "🌬️", name: "Wind Face" },
      { emoji: "🌈", name: "Rainbow" },
  
      // Celestial Bodies
      { emoji: "🌙", name: "Crescent Moon" },
      { emoji: "🌚", name: "New Moon Face" },
      { emoji: "🌝", name: "Full Moon Face" },
      { emoji: "🌞", name: "Sun with Face" },
      { emoji: "⭐️", name: "Star" },
      { emoji: "🌟", name: "Glowing Star" },
      { emoji: "🌠", name: "Shooting Star" },
      { emoji: "☄️", name: "Comet" },
  
      // Miscellaneous
      { emoji: "🔥", name: "Fire" },
      { emoji: "💧", name: "Droplet" },
      { emoji: "🌊", name: "Water Wave" },
      { emoji: "❄️", name: "Snowflake" },
      { emoji: "⛄", name: "Snowman" },
      { emoji: "⚡", name: "High Voltage" },
      { emoji: "💨", name: "Dashing Away" },
    ],
    symbols: [
      { emoji: "💟", name: "Heart Decoration" },
      { emoji: "☮️", name: "Peace Symbol" },
      { emoji: "✝️", name: "Latin Cross" },
      { emoji: "☪️", name: "Star and Crescent" },
      { emoji: "🪯", name: "Wink" },
      { emoji: "🕉", name: "Om" },
      { emoji: "☸️", name: "Wheel of Dharma" },
      { emoji: "✡️", name: "Star of David" },
      { emoji: "🔯", name: "Six Pointed Star" },
      { emoji: "🕎", name: "Menorah" },
      { emoji: "☯️", name: "Yin Yang" },
      { emoji: "☦️", name: "Orthodox Cross" },
      { emoji: "🛐", name: "Place of Worship" },
      { emoji: "⛎", name: "Ophiuchus" },
      { emoji: "♈️", name: "Aries" },
      { emoji: "♉️", name: "Taurus" },
      { emoji: "♊️", name: "Gemini" },
      { emoji: "♋️", name: "Cancer" },
      { emoji: "♌️", name: "Leo" },
      { emoji: "♍️", name: "Virgo" },
      { emoji: "♎️", name: "Libra" },
      { emoji: "♏️", name: "Scorpio" },
      { emoji: "♐️", name: "Sagittarius" },
      { emoji: "♑️", name: "Capricorn" },
      { emoji: "♒️", name: "Aquarius" },
      { emoji: "♓️", name: "Pisces" },
      { emoji: "🆔", name: "ID Button" },
      { emoji: "⚛️", name: "Atom Symbol" },
      { emoji: "🉑", name: "Japanese “Acceptable” Button" },
      { emoji: "☢️", name: "Radioactive" },
      { emoji: "☣️", name: "Biohazard" },
      { emoji: "📴", name: "No Mobile Phones" },
      { emoji: "📳", name: "Vibration Mode" },
      { emoji: "🈶", name: "Japanese “Available” Button" },
      { emoji: "🈚️", name: "Japanese “Free of Charge” Button" },
      { emoji: "🈸", name: "Japanese “Application” Button" },
      { emoji: "🈺", name: "Japanese “Reserved” Button" },
      { emoji: "🈷️", name: "Japanese “Monthly Amount” Button" },
      { emoji: "✴️", name: "Eight Pointed Star" },
      { emoji: "🆚", name: "Versus Button" },
      { emoji: "💮", name: "White Flower" },
      { emoji: "🉐", name: "Japanese “Prohibited” Button" },
      { emoji: "㊙️", name: "Japanese “Secret” Button" },
      { emoji: "㊗️", name: "Japanese “Congratulations” Button" },
      { emoji: "🈴", name: "Japanese “Passing Grade” Button" },
      { emoji: "🈵", name: "Japanese “Full Marks” Button" },
      { emoji: "🈹", name: "Japanese “Discount” Button" },
      { emoji: "🈲", name: "Japanese “Prohibited” Button" },
      { emoji: "🅰️", name: "A Button" },
      { emoji: "🅱️", name: "B Button" },
      { emoji: "🆎", name: "AB Button" },
      { emoji: "🆑", name: "CL Button" },
      { emoji: "🅾️", name: "O Button" },
      { emoji: "🆘", name: "SOS Button" },
      { emoji: "❌", name: "Cross Mark" },
      { emoji: "⭕️", name: "Circle" },
      { emoji: "🛑", name: "Stop Sign" },
      { emoji: "⛔️", name: "Prohibited" },
      { emoji: "📛", name: "Name Badge" },
      { emoji: "🚫", name: "No Entry" },
      { emoji: "💯", name: "Hundred Points" },
      { emoji: "💢", name: "Anger Symbol" },
      { emoji: "♨️", name: "Hot Springs" },
      { emoji: "🚷", name: "No Pedestrians" },
      { emoji: "🚯", name: "No Littering" },
      { emoji: "🚳", name: "No Bicycles" },
      { emoji: "🚱", name: "No Drinking" },
      { emoji: "🔞", name: "No One Under 18" },
      { emoji: "📵", name: "No Mobile Phones" },
      { emoji: "🚭", name: "No Smoking" },
      { emoji: "❗️", name: "Exclamation Mark" },
      { emoji: "❕", name: "White Exclamation Mark" },
      { emoji: "❓", name: "Question Mark" },
      { emoji: "❔", name: "White Question Mark" },
      { emoji: "‼️", name: "Double Exclamation Mark" },
      { emoji: "⁉️", name: "Exclamation Question Mark" },
      { emoji: "🔅", name: "Dim Button" },
      { emoji: "🔆", name: "Bright Button" },
      { emoji: "〽️", name: "Part Alternation Mark" },
      { emoji: "⚠️", name: "Warning" },
      { emoji: "🚸", name: "Children Crossing" },
      { emoji: "🔱", name: "Trident Emblem" },
      { emoji: "⚜️", name: "Fleur-de-lis" },
      { emoji: "🔰", name: "Japanese Beginner Button" },
      { emoji: "♻️", name: "Recycling Symbol" },
      { emoji: "✅", name: "Check Mark" },
      { emoji: "🈯️", name: "Japanese “Reserved” Button" },
      { emoji: "💹", name: "Chart Increasing" },
      { emoji: "❇️", name: "Sparkle" },
      { emoji: "✳️", name: "Eight Spoked Asterisk" },
      { emoji: "❎", name: "Negative Squared Cross Mark" },
      { emoji: "🌐", name: "Globe with Meridians" },
      { emoji: "💠", name: "Diamond with a Dot" },
      { emoji: "Ⓜ️", name: "Circled M" },
      { emoji: "🌀", name: "Cyclone" },
      { emoji: "💤", name: "ZZZ" },
      { emoji: "🏧", name: "ATM Sign" },
      { emoji: "🚾", name: "Water Closet" },
      { emoji: "♿️", name: "Wheelchair Symbol" },
      { emoji: "🅿️", name: "P Button" },
      { emoji: "🛗", name: "Elevator" },
      { emoji: "🈳", name: "Japanese “Vacancy” Button" },
      { emoji: "🈂️", name: "Japanese “Service Charge” Button" },
      { emoji: "🛂", name: "Customs" },
      { emoji: "🛃", name: "Customs" },
      { emoji: "🛄", name: "Baggage Claim" },
      { emoji: "🛅", name: "Left Luggage" },
      { emoji: "🚹", name: "Men’s Room" },
      { emoji: "🚺", name: "Women’s Room" },
      { emoji: "🚼", name: "Baby Symbol" },
      { emoji: "⚧", name: "Transgender Symbol" },
      { emoji: "🚻", name: "Restroom" },
      { emoji: "🚮", name: "Litter in Bin Sign" },
      { emoji: "🎦", name: "Cinema" },
      { emoji: "🛜", name: "Circuit" },
      { emoji: "📶", name: "Antenna Bars" },
      { emoji: "🈁", name: "Japanese “You” Button" },
      { emoji: "🔣", name: "Input Symbol for Symbols" },
      { emoji: "ℹ️", name: "Information" },
      { emoji: "🔤", name: "Input Latin Letters" },
      { emoji: "🔡", name: "Input Letters" },
      { emoji: "🔠", name: "Input Letters" },
      { emoji: "🆖", name: "Squared NG" },
      { emoji: "🆗", name: "Squared OK" },
      { emoji: "🆙", name: "Squared Up" },
      { emoji: "🆒", name: "Squared Cool" },
      { emoji: "🆕", name: "Squared New" },
      { emoji: "🆓", name: "Squared Free" },
      { emoji: "0️⃣", name: "Keycap 0" },
      { emoji: "1️⃣", name: "Keycap 1" },
      { emoji: "2️⃣", name: "Keycap 2" },
      { emoji: "3️⃣", name: "Keycap 3" },
      { emoji: "4️⃣", name: "Keycap 4" },
      { emoji: "5️⃣", name: "Keycap 5" },
      { emoji: "6️⃣", name: "Keycap 6" },
      { emoji: "7️⃣", name: "Keycap 7" },
      { emoji: "8️⃣", name: "Keycap 8" },
      { emoji: "9️⃣", name: "Keycap 9" },
      { emoji: "🔟", name: "Keycap 10" },
      { emoji: "🔢", name: "Input Numbers" },
      { emoji: "#️⃣", name: "Number Sign" },
      { emoji: "*️⃣", name: "Asterisk" },
      { emoji: "⏏️", name: "Eject Button" },
      { emoji: "▶️", name: "Play Button" },
      { emoji: "⏸", name: "Pause Button" },
      { emoji: "⏯", name: "Play or Pause Button" },
      { emoji: "⏹", name: "Stop Button" },
      { emoji: "⏺", name: "Record Button" },
      { emoji: "⏭", name: "Next Track Button" },
      { emoji: "⏮", name: "Previous Track Button" },
      { emoji: "⏩", name: "Fast Forward Button" },
      { emoji: "⏪", name: "Rewind Button" },
      { emoji: "⏫", name: "Fast Up Button" },
      { emoji: "⏬", name: "Fast Down Button" },
      { emoji: "◀️", name: "Leftwards Button" },
      { emoji: "🔼", name: "Upwards Button" },
      { emoji: "🔽", name: "Downwards Button" },
      { emoji: "➡️", name: "Rightwards Button" },
      { emoji: "⬅️", name: "Leftwards Button" },
      { emoji: "⬆️", name: "Upwards Button" },
      { emoji: "⬇️", name: "Downwards Button" },
      { emoji: "↗️", name: "Up-Right Button" },
      { emoji: "↘️", name: "Down-Right Button" },
      { emoji: "↙️", name: "Down-Left Button" },
      { emoji: "↖️", name: "Up-Left Button" },
      { emoji: "↕️", name: "Up-Down Button" },
      { emoji: "↔️", name: "Left-Right Button" },
      { emoji: "↪️", name: "Rightwards Arrow with Hook" },
      { emoji: "↩️", name: "Leftwards Arrow with Hook" },
      { emoji: "⤴️", name: "Rightwards Arrow with Hook" },
      { emoji: "⤵️", name: "Leftwards Arrow with Hook" },
      { emoji: "🔀", name: "Shuffle Tracks Button" },
      { emoji: "🔁", name: "Repeat Button" },
      { emoji: "🔂", name: "Repeat One Button" },
      { emoji: "🔄", name: "Arrows in a Circle" },
      { emoji: "🔃", name: "Arrows in a Circle" },
      { emoji: "🎵", name: "Musical Note" },
      { emoji: "🎶", name: "Musical Notes" },
      { emoji: "➕", name: "Plus" },
      { emoji: "➖", name: "Minus" },
      { emoji: "➗", name: "Divide" },
      { emoji: "✖️", name: "Multiplication" },
      { emoji: "🟰", name: "Equal" },
      { emoji: "♾", name: "Infinity" },
      { emoji: "💲", name: "Dollar Sign" },
      { emoji: "💱", name: "Currency Exchange" },
      { emoji: "™️", name: "Trademark" },
      { emoji: "©️", name: "Copyright" },
      { emoji: "®️", name: "Registered Trademark" },
      { emoji: "〰️", name: "Wavy Dash" },
      { emoji: "➰", name: "Curly Loop" },
      { emoji: "➿", name: "Double Curly Loop" },
      { emoji: "🔚", name: "Backwards Button" },
      { emoji: "🔙", name: "Backwards Button" },
      { emoji: "🔛", name: "Leftwards Button" },
      { emoji: "🔝", name: "Upwards Button" },
      { emoji: "🔜", name: "Rightwards Button" },
      { emoji: "✔️", name: "Check Mark" },
      { emoji: "☑️", name: "Check Box with Check" },
      { emoji: "🔘", name: "Radio Button" },
      { emoji: "🔴", name: "Red Circle" },
      { emoji: "🟠", name: "Orange Circle" },
      { emoji: "🟡", name: "Yellow Circle" },
      { emoji: "🟢", name: "Green Circle" },
      { emoji: "🔵", name: "Blue Circle" },
      { emoji: "🟣", name: "Purple Circle" },
      { emoji: "⚫️", name: "Black Circle" },
      { emoji: "⚪️", name: "White Circle" },
      { emoji: "🟤", name: "Brown Circle" },
      { emoji: "🔺", name: "Red Triangle" },
      { emoji: "🔻", name: "Downwards Button" },
      { emoji: "🔸", name: "Small Orange Diamond" },
      { emoji: "🔹", name: "Small Blue Diamond" },
      { emoji: "🔶", name: "Large Orange Diamond" },
      { emoji: "🔷", name: "Large Blue Diamond" },
      { emoji: "🔳", name: "White Square with Rounded Corners" },
      { emoji: "🔲", name: "Black Square with Rounded Corners" },
      { emoji: "▪️", name: "Black Small Square" },
      { emoji: "▫️", name: "White Small Square" },
      { emoji: "◾️", name: "Black Medium Square" },
      { emoji: "◽️", name: "White Medium Square" },
      { emoji: "◼️", name: "Black Medium-Small Square" },
      { emoji: "◻️", name: "White Medium-Small Square" },
      { emoji: "🟥", name: "Red Square" },
      { emoji: "🟧", name: "Orange Square" },
      { emoji: "🟨", name: "Yellow Square" },
      { emoji: "🟩", name: "Green Square" },
      { emoji: "🟦", name: "Blue Square" },
      { emoji: "🟪", name: "Purple Square" },
      { emoji: "⬛️", name: "Black Large Square" },
      { emoji: "⬜️", name: "White Large Square" },
      { emoji: "🟫", name: "Brown Square" },
      { emoji: "🔈", name: "Speaker with No Sound" },
      { emoji: "🔇", name: "Speaker Muted" },
      { emoji: "🔉", name: "Speaker with Low Sound" },
      { emoji: "🔊", name: "Speaker with High Sound" },
      { emoji: "🔔", name: "Bell" },
      { emoji: "🔕", name: "Bell with Slash" },
      { emoji: "📣", name: "Loudspeaker" },
      { emoji: "📢", name: "Megaphone" },
      { emoji: "👁‍🗨", name: "Eye in Speech Bubble" },
      { emoji: "💬", name: "Speech Balloon" },
      { emoji: "💭", name: "Thought Balloon" },
      { emoji: "🗯", name: "Right Anger Bubble" },
      { emoji: "♠️", name: "Spade Suit" },
      { emoji: "♣️", name: "Club Suit" },
      { emoji: "♦️", name: "Diamond Suit" },
      { emoji: "♥️", name: "Heart Suit" },
      { emoji: "🃏", name: "Joker" }
    ],
    objects: [
      { emoji: "📱", name: "Mobile Phone" },
      { emoji: "💻", name: "Laptop" },
      { emoji: "🖥", name: "Desktop Computer" },
      { emoji: "🖨", name: "Printer" },
      { emoji: "⌨️", name: "Keyboard" },
      { emoji: "🖱", name: "Computer Mouse" },
      { emoji: "🖲", name: "Trackball" },
      { emoji: "💾", name: "Floppy Disk" },
      { emoji: "💿", name: "Optical Disk" },
      { emoji: "📀", name: "DVD" },
      { emoji: "🎥", name: "Movie Camera" },
      { emoji: "📸", name: "Camera with Flash" },
      { emoji: "📷", name: "Camera" },
      { emoji: "📹", name: "Video Camera" },
      { emoji: "📼", name: "VHS Tape" },
      { emoji: "🔋", name: "Battery" },
      { emoji: "🔌", name: "Electric Plug" },
      { emoji: "💡", name: "Light Bulb" },
      { emoji: "🔦", name: "Flashlight" },
      { emoji: "🕯", name: "Candle" },
      { emoji: "🪔", name: "Diya Lamp" },
      { emoji: "💨", name: "Dashing Away" },
      { emoji: "🚪", name: "Door" },
      { emoji: "🛋", name: "Couch and Lamp" },
      { emoji: "🛏", name: "Bed" },
      { emoji: "🚪", name: "Door" },
      { emoji: "🏠", name: "House" },
      { emoji: "🏡", name: "House with Garden" },
      { emoji: "🏢", name: "Office Building" },
      { emoji: "🏣", name: "Japanese Post Office" },
      { emoji: "🏤", name: "Post Office" },
      { emoji: "🏥", name: "Hospital" },
      { emoji: "🏦", name: "Bank" },
      { emoji: "🏨", name: "Hotel" },
      { emoji: "🏩", name: "Love Hotel" },
      { emoji: "🏪", name: "Convenience Store" },
      { emoji: "🏫", name: "School" },
      { emoji: "🏬", name: "Department Store" },
      { emoji: "🏭", name: "Factory" },
      { emoji: "🏯", name: "Japanese Castle" },
      { emoji: "🏰", name: "Castle" }
    ],    
    places: [
      { emoji: "🏠", name: "House" },
      { emoji: "🏡", name: "House with Garden" },
      { emoji: "🏢", name: "Office Building" },
      { emoji: "🏣", name: "Japanese Post Office" },
      { emoji: "🏤", name: "Post Office" },
      { emoji: "🏥", name: "Hospital" },
      { emoji: "🏦", name: "Bank" },
      { emoji: "🏨", name: "Hotel" },
      { emoji: "🏩", name: "Love Hotel" },
      { emoji: "🏪", name: "Convenience Store" },
      { emoji: "🏫", name: "School" },
      { emoji: "🏬", name: "Department Store" },
      { emoji: "🏭", name: "Factory" },
      { emoji: "🏯", name: "Japanese Castle" },
      { emoji: "🏰", name: "Castle" },
      { emoji: "🏗️", name: "Building Construction" },
      { emoji: "🌇", name: "Sunset Over Buildings" },
      { emoji: "🌆", name: "Cityscape at Dusk" },
      { emoji: "🌉", name: "Bridge at Night" },
      { emoji: "🏙️", name: "Cityscape" },
      { emoji: "🌌", name: "Milky Way" },
      { emoji: "🏞️", name: "National Park" },
      { emoji: "🌅", name: "Sunrise" },
      { emoji: "🏖️", name: "Beach with Umbrella" },
      { emoji: "🏝️", name: "Desert Island" },
      { emoji: "🏜️", name: "Desert" },
      { emoji: "🏞️", name: "Park" },
      { emoji: "🌄", name: "Sunrise Over Mountains" },
      { emoji: "🌅", name: "Sunrise" },
      { emoji: "🏔️", name: "Snow-Capped Mountain" },
      { emoji: "🌋", name: "Volcano" },
      { emoji: "🗻", name: "Mountain" },
      { emoji: "🏞️", name: "National Park" },
      { emoji: "🌍", name: "Earth Globe Europe-Africa" },
      { emoji: "🌎", name: "Earth Globe Americas" },
      { emoji: "🌏", name: "Earth Globe Asia-Australia" },
      { emoji: "🗺️", name: "World Map" },
    ],
    flags: [
      { emoji: "🏳️", name: "White Flag" },
      { emoji: "🏴", name: "Black Flag" },
      { emoji: "🏁", name: "Chequered Flag" },
      { emoji: "🚩", name: "Triangular Flag" },
      { emoji: "🏳️‍🌈", name: "Rainbow Flag" },
      { emoji: "🏳️‍⚧️", name: "Transgender Flag" },
      { emoji: "🏴‍☠️", name: "Pirate Flag" },
      { emoji: "🇦🇫", name: "Flag of Afghanistan" },
      { emoji: "🇦🇽", name: "Flag of Åland Islands" },
      { emoji: "🇦🇱", name: "Flag of Albania" },
      { emoji: "🇩🇿", name: "Flag of Algeria" },
      { emoji: "🇦🇸", name: "Flag of American Samoa" },
      { emoji: "🇦🇩", name: "Flag of Andorra" },
      { emoji: "🇦🇴", name: "Flag of Angola" },
      { emoji: "🇦🇮", name: "Flag of Anguilla" },
      { emoji: "🇦🇶", name: "Flag of Antarctica" },
      { emoji: "🇦🇬", name: "Flag of Antigua and Barbuda" },
      { emoji: "🇦🇷", name: "Flag of Argentina" },
      { emoji: "🇦🇲", name: "Flag of Armenia" },
      { emoji: "🇦🇼", name: "Flag of Aruba" },
      { emoji: "🇦🇺", name: "Flag of Australia" },
      { emoji: "🇦🇹", name: "Flag of Austria" },
      { emoji: "🇦🇿", name: "Flag of Azerbaijan" },
      { emoji: "🇧🇸", name: "Flag of Bahamas" },
      { emoji: "🇧🇭", name: "Flag of Bahrain" },
      { emoji: "🇧🇩", name: "Flag of Bangladesh" },
      { emoji: "🇧🇧", name: "Flag of Barbados" },
      { emoji: "🇧🇾", name: "Flag of Belarus" },
      { emoji: "🇧🇪", name: "Flag of Belgium" },
      { emoji: "🇧🇿", name: "Flag of Belize" },
      { emoji: "🇧🇯", name: "Flag of Benin" },
      { emoji: "🇧🇲", name: "Flag of Bermuda" },
      { emoji: "🇧🇹", name: "Flag of Bhutan" },
      { emoji: "🇧🇴", name: "Flag of Bolivia" },
      { emoji: "🇧🇦", name: "Flag of Bosnia and Herzegovina" },
      { emoji: "🇧🇼", name: "Flag of Botswana" },
      { emoji: "🇧🇷", name: "Flag of Brazil" },
      { emoji: "🇮🇴", name: "British Indian Ocean Territory Flag" },
      { emoji: "🇻🇬", name: "British Virgin Islands Flag" },
      { emoji: "🇧🇳", name: "Flag of Brunei" },
      { emoji: "🇧🇬", name: "Flag of Bulgaria" },
      { emoji: "🇧🇫", name: "Flag of Burkina Faso" },
      { emoji: "🇧🇮", name: "Flag of Burundi" },
      { emoji: "🇰🇭", name: "Flag of Cambodia" },
      { emoji: "🇨🇲", name: "Flag of Cameroon" },
      { emoji: "🇨🇦", name: "Flag of Canada" },
      { emoji: "🇮🇨", name: "Flag of Canary Islands" },
      { emoji: "🇨🇻", name: "Flag of Cape Verde" },
      { emoji: "🇧🇶", name: "Caribbean Netherlands Flag" },
      { emoji: "🇰🇾", name: "Cayman Islands Flag" },
      { emoji: "🇨🇫", name: "Central African Republic Flag" },
      { emoji: "🇹🇩", name: "Flag of Chad" },
      { emoji: "🇨🇱", name: "Flag of Chile" },
      { emoji: "🇨🇳", name: "Flag of China" },
      { emoji: "🇨🇽", name: "Christmas Island Flag" },
      { emoji: "🇨🇨", name: "Cocos (Keeling) Islands Flag" },
      { emoji: "🇨🇴", name: "Flag of Colombia" },
      { emoji: "🇰🇲", name: "Flag of Comoros" },
      { emoji: "🇨🇬", name: "Flag of Congo" },
      { emoji: "🇨🇩", name: "Flag of the Democratic Republic of the Congo" },
      { emoji: "🇨🇰", name: "Cook Islands Flag" },
      { emoji: "🇨🇷", name: "Flag of Costa Rica" },
      { emoji: "🇨🇮", name: "Flag of Côte d'Ivoire" },
      { emoji: "🇭🇷", name: "Flag of Croatia" },
      { emoji: "🇨🇺", name: "Flag of Cuba" },
      { emoji: "🇨🇼", name: "Flag of Curaçao" },
      { emoji: "🇨🇾", name: "Flag of Cyprus" },
      { emoji: "🇨🇿", name: "Flag of Czech Republic" },
      { emoji: "🇩🇰", name: "Flag of Denmark" },
      { emoji: "🇩🇯", name: "Flag of Djibouti" },
      { emoji: "🇩🇲", name: "Flag of Dominica" },
      { emoji: "🇩🇴", name: "Flag of Dominican Republic" },
      { emoji: "🇪🇨", name: "Flag of Ecuador" },
      { emoji: "🇪🇬", name: "Flag of Egypt" },
      { emoji: "🇸🇻", name: "Flag of El Salvador" },
      { emoji: "🇬🇶", name: "Flag of Equatorial Guinea" },
      { emoji: "🇪🇷", name: "Flag of Eritrea" },
      { emoji: "🇪🇪", name: "Flag of Estonia" },
      { emoji: "🇪🇹", name: "Flag of Ethiopia" },
      { emoji: "🇪🇺", name: "European Union Flag" },
      { emoji: "🇫🇰", name: "Falkland Islands Flag" },
      { emoji: "🇫🇴", name: "Flag of Faroe Islands" },
      { emoji: "🇫🇯", name: "Flag of Fiji" },
      { emoji: "🇫🇮", name: "Flag of Finland" },
      { emoji: "🇫🇷", name: "Flag of France" },
      { emoji: "🇬🇫", name: "French Guiana Flag" },
      { emoji: "🇵🇫", name: "French Polynesia Flag" },
      { emoji: "🇹🇫", name: "French Southern and Antarctic Lands Flag" },
      { emoji: "🇬🇦", name: "Flag of Gabon" },
      { emoji: "🇬🇲", name: "Flag of Gambia" },
      { emoji: "🇬🇪", name: "Flag of Georgia" },
      { emoji: "🇩🇪", name: "Flag of Germany" },
      { emoji: "🇬🇭", name: "Flag of Ghana" },
      { emoji: "🇬🇮", name: "Flag of Gibraltar" },
      { emoji: "🇬🇷", name: "Flag of Greece" },
      { emoji: "🇬🇱", name: "Flag of Greenland" },
      { emoji: "🇬🇩", name: "Flag of Grenada" },
      { emoji: "🇬🇵", name: "Flag of Guadeloupe" },
      { emoji: "🇬🇺", name: "Flag of Guam" },
      { emoji: "🇬🇹", name: "Flag of Guatemala" },
      { emoji: "🇬🇬", name: "Guernsey Flag" },
      { emoji: "🇬🇳", name: "Flag of Guinea" },
      { emoji: "🇬🇼", name: "Flag of Guinea-Bissau" },
      { emoji: "🇬🇾", name: "Flag of Guyana" },
      { emoji: "🇭🇹", name: "Flag of Haiti" },
      { emoji: "🇭🇳", name: "Flag of Honduras" },
      { emoji: "🇭🇰", name: "Flag of Hong Kong" },
      { emoji: "🇭🇺", name: "Flag of Hungary" },
      { emoji: "🇮🇸", name: "Flag of Iceland" },
      { emoji: "🇮🇳", name: "Flag of India" },
      { emoji: "🇮🇩", name: "Flag of Indonesia" },
      { emoji: "🇮🇷", name: "Flag of Iran" },
      { emoji: "🇮🇶", name: "Flag of Iraq" },
      { emoji: "🇮🇪", name: "Flag of Ireland" },
      { emoji: "🇮🇲", name: "Isle of Man Flag" },
      { emoji: "🇮🇱", name: "Flag of Israel" },
      { emoji: "🇮🇹", name: "Flag of Italy" },
      { emoji: "🇯🇲", name: "Flag of Jamaica" },
      { emoji: "🇯🇵", name: "Flag of Japan" },
      { emoji: "🎌", name: "Flag of Japan (alternative design)" },
      { emoji: "🇯🇪", name: "Flag of Jersey" },
      { emoji: "🇯🇴", name: "Flag of Jordan" },
      { emoji: "🇰🇿", name: "Flag of Kazakhstan" },
      { emoji: "🇰🇪", name: "Flag of Kenya" },
      { emoji: "🇰🇮", name: "Flag of Kiribati" },
      { emoji: "🇽🇰", name: "Flag of Kosovo" },
      { emoji: "🇰🇼", name: "Flag of Kuwait" },
      { emoji: "🇰🇬", name: "Flag of Kyrgyzstan" },
      { emoji: "🇱🇦", name: "Flag of Laos" },
      { emoji: "🇱🇻", name: "Flag of Latvia" },
      { emoji: "🇱🇧", name: "Flag of Lebanon" },
      { emoji: "🇱🇸", name: "Flag of Lesotho" },
      { emoji: "🇱🇷", name: "Flag of Liberia" },
      { emoji: "🇱🇾", name: "Flag of Libya" },
      { emoji: "🇱🇮", name: "Flag of Liechtenstein" },
      { emoji: "🇱🇹", name: "Flag of Lithuania" },
      { emoji: "🇱🇺", name: "Flag of Luxembourg" },
      { emoji: "🇲🇴", name: "Flag of Macau" },
      { emoji: "🇲🇰", name: "Flag of North Macedonia" },
      { emoji: "🇲🇬", name: "Flag of Madagascar" },
      { emoji: "🇲🇼", name: "Flag of Malawi" },
      { emoji: "🇲🇾", name: "Flag of Malaysia" },
      { emoji: "🇲🇻", name: "Flag of Maldives" },
      { emoji: "🇲🇱", name: "Flag of Mali" },
      { emoji: "🇲🇹", name: "Flag of Malta" },
      { emoji: "🇲🇭", name: "Flag of Marshall Islands" },
      { emoji: "🇲🇶", name: "Flag of Martinique" },
      { emoji: "🇲🇷", name: "Flag of Mauritania" },
      { emoji: "🇲🇺", name: "Flag of Mauritius" },
      { emoji: "🇾🇹", name: "Flag of Mayotte" },
      { emoji: "🇲🇽", name: "Flag of Mexico" },
      { emoji: "🇫🇲", name: "Flag of Micronesia" },
      { emoji: "🇲🇩", name: "Flag of Moldova" },
      { emoji: "🇲🇨", name: "Flag of Monaco" },
      { emoji: "🇲🇳", name: "Flag of Mongolia" },
      { emoji: "🇲🇪", name: "Flag of Montenegro" },
      { emoji: "🇲🇸", name: "Flag of Montserrat" },
      { emoji: "🇲🇦", name: "Flag of Morocco" },
      { emoji: "🇲🇿", name: "Flag of Mozambique" },
      { emoji: "🇲🇲", name: "Flag of Myanmar" },
      { emoji: "🇳🇦", name: "Flag of Namibia" },
      { emoji: "🇳🇷", name: "Flag of Nauru" },
      { emoji: "🇳🇵", name: "Flag of Nepal" },
      { emoji: "🇳🇱", name: "Flag of Netherlands" },
      { emoji: "🇳🇨", name: "New Caledonia Flag" },
      { emoji: "🇳🇿", name: "Flag of New Zealand" },
      { emoji: "🇳🇮", name: "Flag of Nicaragua" },
      { emoji: "🇳🇪", name: "Flag of Niger" },
      { emoji: "🇳🇬", name: "Flag of Nigeria" },
      { emoji: "🇳🇺", name: "Flag of Niue" },
      { emoji: "🇳🇫", name: "Norfolk Island Flag" },
      { emoji: "🇰🇵", name: "Flag of North Korea" },
      { emoji: "🇲🇵", name: "Northern Mariana Islands Flag" },
      { emoji: "🇳🇴", name: "Flag of Norway" },
      { emoji: "🇴🇲", name: "Flag of Oman" },
      { emoji: "🇵🇰", name: "Flag of Pakistan" },
      { emoji: "🇵🇼", name: "Flag of Palau" },
      { emoji: "🇵🇸", name: "Flag of Palestine" },
      { emoji: "🇵🇦", name: "Flag of Panama" },
      { emoji: "🇵🇬", name: "Flag of Papua New Guinea" },
      { emoji: "🇵🇾", name: "Flag of Paraguay" },
      { emoji: "🇵🇪", name: "Flag of Peru" },
      { emoji: "🇵🇭", name: "Flag of Philippines" },
      { emoji: "🇵🇳", name: "Pitcairn Islands Flag" },
      { emoji: "🇵🇱", name: "Flag of Poland" },
      { emoji: "🇵🇹", name: "Flag of Portugal" },
      { emoji: "🇵🇷", name: "Flag of Puerto Rico" },
      { emoji: "🇶🇦", name: "Flag of Qatar" },
      { emoji: "🇷🇪", name: "Réunion Flag" },
      { emoji: "🇷🇴", name: "Flag of Romania" },
      { emoji: "🇷🇺", name: "Flag of Russia" },
      { emoji: "🇷🇼", name: "Flag of Rwanda" },
      { emoji: "🇼🇸", name: "Flag of Samoa" },
      { emoji: "🇸🇲", name: "San Marino Flag" },
      { emoji: "🇸🇦", name: "Flag of Saudi Arabia" },
      { emoji: "🇸🇳", name: "Flag of Senegal" },
      { emoji: "🇷🇸", name: "Flag of Serbia" },
      { emoji: "🇸🇨", name: "Flag of Seychelles" },
      { emoji: "🇸🇱", name: "Flag of Sierra Leone" },
      { emoji: "🇸🇬", name: "Flag of Singapore" },
      { emoji: "🇸🇽", name: "Flag of Sint Maarten" },
      { emoji: "🇸🇰", name: "Flag of Slovakia" },
      { emoji: "🇸🇮", name: "Flag of Slovenia" },
      { emoji: "🇬🇸", name: "South Georgia and the South Sandwich Islands Flag" },
      { emoji: "🇸🇧", name: "Flag of Solomon Islands" },
      { emoji: "🇸🇴", name: "Flag of Somalia" },
      { emoji: "🇿🇦", name: "Flag of South Africa" },
      { emoji: "🇰🇷", name: "Flag of South Korea" },
      { emoji: "🇸🇸", name: "Flag of South Sudan" },
      { emoji: "🇪🇸", name: "Flag of Spain" },
      { emoji: "🇱🇰", name: "Flag of Sri Lanka" },
      { emoji: "🇧🇱", name: "Saint Barthélemy Flag" },
      { emoji: "🇸🇭", name: "Saint Helena Flag" },
      { emoji: "🇰🇳", name: "Saint Kitts and Nevis Flag" },
      { emoji: "🇱🇨", name: "Saint Lucia Flag" },
      { emoji: "🇵🇲", name: "Saint Pierre and Miquelon Flag" },
      { emoji: "🇻🇨", name: "Saint Vincent and the Grenadines Flag" },
      { emoji: "🇸🇩", name: "Flag of Sudan" },
      { emoji: "🇸🇷", name: "Flag of Suriname" },
      { emoji: "🇸🇿", name: "Flag of Eswatini" },
      { emoji: "🇸🇪", name: "Flag of Sweden" },
      { emoji: "🇨🇭", name: "Flag of Switzerland" },
      { emoji: "🇸🇾", name: "Flag of Syria" },
      { emoji: "🇹🇼", name: "Flag of Taiwan" },
      { emoji: "🇹🇯", name: "Flag of Tajikistan" },
      { emoji: "🇹🇿", name: "Flag of Tanzania" },
      { emoji: "🇹🇭", name: "Flag of Thailand" },
      { emoji: "🇹🇱", name: "Flag of Timor-Leste" },
      { emoji: "🇹🇬", name: "Flag of Togo" },
      { emoji: "🇹🇰", name: "Flag of Tokelau" },
      { emoji: "🇹🇴", name: "Flag of Tonga" },
      { emoji: "🇹🇹", name: "Flag of Trinidad and Tobago" },
      { emoji: "🇹🇳", name: "Flag of Tunisia" },
      { emoji: "🇹🇷", name: "Flag of Turkey" },
      { emoji: "🇹🇲", name: "Flag of Turkmenistan" },
      { emoji: "🇹🇨", name: "Flag of the Turks and Caicos Islands" },
      { emoji: "🇹🇻", name: "Flag of Tuvalu" },
      { emoji: "🇻🇮", name: "U.S. Virgin Islands Flag" },
      { emoji: "🇺🇬", name: "Flag of Uganda" },
      { emoji: "🇺🇦", name: "Flag of Ukraine" },
      { emoji: "🇦🇪", name: "Flag of United Arab Emirates" },
      { emoji: "🇬🇧", name: "Flag of United Kingdom" },
      { emoji: "🏴", name: "Flag of Unknown Territory" },
      { emoji: "🏴", name: "Flag of Unknown Territory" },
      { emoji: "🏴", name: "Flag of Unknown Territory" },
      { emoji: "🇺🇳", name: "Flag of United Nations" },
      { emoji: "🇺🇸", name: "Flag of United States" },
      { emoji: "🇺🇾", name: "Flag of Uruguay" },
      { emoji: "🇺🇿", name: "Flag of Uzbekistan" },
      { emoji: "🇻🇺", name: "Flag of Vanuatu" },
      { emoji: "🇻🇦", name: "Flag of Vatican City" },
      { emoji: "🇻🇪", name: "Flag of Venezuela" },
      { emoji: "🇻🇳", name: "Flag of Vietnam" },
      { emoji: "🇼🇫", name: "Wallis and Futuna Flag" },
      { emoji: "🇪🇭", name: "Western Sahara Flag" },
      { emoji: "🇾🇪", name: "Flag of Yemen" },
      { emoji: "🇿🇲", name: "Flag of Zambia" },
      { emoji: "🇿🇼", name: "Flag of Zimbabwe" } 
    ]    
  };
  
